### ISSUE TITLE
Issue in macosx: grep: invalid option -- P

### ISSUE THREAD

**Issue by viktor921** [kyhau/saml2aws-multi#83]
found in: saml2aws-multi-1.0.0/install-saml2aws.sh

Issue: grep on macosx do not have option -P for perl regex

solution I've used:

> if [ "$(uname)" == "Darwin" ];
then
&emsp; # macos detected, no grep -P commang avaliable
&emsp; VERSION=$(curl --silent "https://api.github.com/repos/Versent/saml2aws/releases/latest" --insecure -s | grep '"tag_name":' | awk -F "\"" '{print $4}' | sed s'/v//')
else
&emsp;VERSION=$(curl --silent "https://api.github.com/repos/Versent/saml2aws/releases/latest" --insecure -s | grep -Po '"tag_name": "\K.*?(?=")')
&emsp;VERSION="${VERSION:1}"
fi

**Comment by kyhau** [comment]
Hi @viktor921 

Yes, the quick saml2aws installation scripts in the repo only support Linux and Window.

For installation on other platforms, please see README in https://github.com/Versent/saml2aws.
For osx, `brew install saml2aws` is recommended there.

Cheers
